# Generated by Django 2.1.1 on 2018-10-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_nasc',
            field=models.DateTimeField(verbose_name='Data de Nascimento'),
        ),
    ]
