# Generated by Django 2.1.1 on 2018-10-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCad', '0006_auto_20181023_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['id'], 'verbose_name': 'nome', 'verbose_name_plural': 'nomes'},
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF(Somente números)'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nasc',
            field=models.DateField(verbose_name='Data de Nascimento (aaaa/mm/dd)'),
        ),
    ]
