# Generated by Django 2.1.1 on 2018-11-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCad', '0008_auto_20181031_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('profresp', models.CharField(max_length=100, verbose_name='Professores Responsáveis')),
                ('carga', models.IntegerField(verbose_name='Carga Horária')),
                ('coordenador', models.CharField(max_length=100, verbose_name='Coordenador Responsável')),
                ('conteudo', models.CharField(max_length=500, verbose_name='Conteudo Programático')),
                ('curso', models.CharField(max_length=100, verbose_name='Cursos Ministrados')),
            ],
            options={
                'verbose_name': 'nome',
                'verbose_name_plural': 'nomes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF(Somente números)')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento (aaaa-mm-dd)')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('materia', models.CharField(max_length=100, verbose_name='Materia ministrada')),
            ],
            options={
                'verbose_name': 'nome',
                'verbose_name_plural': 'nomes',
                'ordering': ['id'],
            },
        ),
    ]
